# El traceback nos da un seguimiendo de donde sali칩 el error
# para poder debuguear m치s r치pido

# Para trabjar con la excepciones con Python obligatoriamente
# vamos a tener que trabajar con dos bloques Try - Except

# En Try ponemos el c칩digo que puede dar error
# Y en Except lo que queremos que se ejecute si da el error

num_1 = 10
num_2 = 0

result = num_1 / num_2

print("El resultado de la operacion es:", result)
print("El programa ha finalizado.")